import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { Layout, Input, Space } from 'antd'
import 'antd/dist/antd.css'
import { useState } from 'react'
import LoginForm from '../components/LoginForm'

const Home: NextPage = () => {
  const { Header, Footer, Content } = Layout
  const { Search } = Input
  const [loginFormVisible, setLoginFormVisible] = useState<boolean>(true)

  const toggleLoginForm = () => {
    setLoginFormVisible((prevState: boolean) => !prevState)
  }

  const handleCancel = () => {
    setLoginFormVisible((prevState: boolean) => !prevState)
  }

  return (
    <>
      <Head>
        <title>Landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className={styles.container}>
        <Header className={styles.header}>
          <Image
            src="/images/logo-new-2.png"
            alt="trueID-logo"
            width="120"
            height="40"
          />
          <ul className={styles.navbar}>
            <li>
              <Link href="/">
                <a>Home</a>
              </Link>
            </li>
            <li>
              <Link href="/">
                <a onClick={toggleLoginForm}>Login</a>
              </Link>
            </li>
          </ul>
        </Header>
        <Content className={styles.main}>
          <LoginForm visible={loginFormVisible} handleCancel={handleCancel} />
          <Space direction="vertical" size="middle">
            <h1 className={styles.title}>trueID landing page</h1>
            <Search
              placeholder="Enter your email address to learn more about us"
              allowClear
              enterButton="Submit"
              size="large"
            />
          </Space>
        </Content>
        <Footer>
          <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{' '}
              <span className={styles.logo}>
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  width={72}
                  height={16}
                />
              </span>
            </a>
          </footer>
        </Footer>
      </Layout>
    </>
  )
}

export default Home
